import sys, turtle, time, string, matplotlib.pyplot, numpy, plotly.express
turtle.title("Picturesque")
turtle.reset()
turtle.left(90)
turtle.forward(100)
turtle.right(45)
turtle.forward(70)
turtle.right(90)
turtle.forward(70)
turtle.right(45)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.mainloop()